Models/AmDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ActivityManagement.Services;
using Microsoft.EntityFrameworkCore;

namespace ActivityManagement.Models
{
    public class AmDbContext : DbContext
    {
        public AmDbContext (DbContextOptions<AmDbContext> options) : base (options)
        {

        }
        public DbSet<Obra> Obra { get; set; }

        public DbSet<Usuario> Usuario { get; set; }

        public DbSet<ViewPainelProjetos> VwProjetos { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ActivityManagement.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Foto.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;

namespace ActivityManagement.Models
{
    public class Foto
    {
        public int Id { get; set; }
        public Image Imagem { get; set; }
        public int ProjetoId { get; set; }
    }
}

Models/Obra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ActivityManagement.Models
{
    public class Obra
    {
        public int Id { get; set; }
        public DateTime Inicio { get; set; }
        public DateTime Previsao { get; set; }
        public DateTime Termino { get; set; }
        public string IdentificacaoDoProjeto { get; set; }
        public string ChefeDaObra { get; set; }
        public int Status { get; set; }
        public string UF { get; set; }
        public string Municipio { get; set; }
        public int Progresso { get; set; } = 0; 
    }
}

Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ActivityManagement.Models
{
    public class Usuario
    {
        public Usuario(int id, string nome, int cargoId, string login, string senha)
        {
            Id = id;
            Nome = nome;
            CargoId = cargoId;
            Login = login;
            Senha = senha;
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public int CargoId { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ActivityManagement.Models;

namespace ActivityManagement.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Projects()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ObraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ActivityManagement.Models;
using ActivityManagement.Services;

namespace ActivityManagement.Controllers
{
    public class ObraController : Controller
    {
        private readonly AmDbContext _context;

        public ObraController(AmDbContext context)
        {
            _context = context;
        }

        // GET: Obra
        public async Task<IActionResult> Index()
        {

            var resultSet = _context.VwProjetos.FromSqlRaw("SELECT * FROM VW_PAINEL_PROJETOS").ToList();
            ViewBag.oPainelProjetos = resultSet;

            return _context.Obra != null ?
                        View(await _context.Obra.ToListAsync()) :
                        Problem("Entity set 'AmDbContext.Obra'  is null.");
        }

        // GET: Obra/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Obra == null)
            {
                return NotFound();
            }

            var obra = await _context.Obra
                .FirstOrDefaultAsync(m => m.Id == id);
            if (obra == null)
            {
                return NotFound();
            }

            return View(obra);
        }

        // GET: Obra/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Obra/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Inicio,Previsao,Termino,IdentificacaoDoProjeto,ChefeDaObra,Status,UF,Municipio")] Obra obra)
        {
            _context.Add(obra);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Obra/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Obra == null)
            {
                return NotFound();
            }

            var obra = await _context.Obra.FindAsync(id);
            if (obra == null)
            {
                return NotFound();
            }
            return View(obra);
        }

        // POST: Obra/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Inicio,Previsao,Termino,ResponsavelGeral,ChefeDaObra,Status,UF,Municipio")] Obra obra)
        {
            if (id != obra.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(obra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ObraExists(obra.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(obra);
        }

        // GET: Obra/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Obra == null)
            {
                return NotFound();
            }

            var obra = await _context.Obra
                .FirstOrDefaultAsync(m => m.Id == id);
            if (obra == null)
            {
                return NotFound();
            }

            return View(obra);
        }

        // POST: Obra/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Obra == null)
            {
                return Problem("Entity set 'AmDbContext.Obra'  is null.");
            }
            var obra = await _context.Obra.FindAsync(id);
            if (obra != null)
            {
                _context.Obra.Remove(obra);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ObraExists(int id)
        {
            return (_context.Obra?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Painel";
}
</nav>
<div class="content">
    <div class="container-fluid p-0">
        <h1 class="h3 mb-3"><strong>Painel</strong> Principal</h1>
        <div class="row">
            <div class="col-xl-6 col-xxl-5 d-flex">
                <div class="w-100">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col mt-0">
                                            <h5 class="card-title">Projetos concluídas</h5>
                                        </div>
                                        <div class="col-auto">
                                            <div class="stat text-primary">
                                                <i class="align-middle" data-feather="check-circle"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <h1 class="mt-1 mb-3">2.382</h1>
                                    <div class="mb-0">
                                        <span class="text-danger"> <i class="mdi mdi-arrow-bottom-right"></i> -3.65%
                                        </span>
                                        <span class="text-muted">Since last week</span>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col mt-0">
                                            <h5 class="card-title">Projetos em andamento</h5>
                                        </div>

                                        <div class="col-auto">
                                            <div class="stat text-primary">
                                                <i class="align-middle" data-feather="loader"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <h1 class="mt-1 mb-3">14.212</h1>
                                    <div class="mb-0">
                                        <span class="text-success"> <i class="mdi mdi-arrow-bottom-right"></i> 5.25%
                                        </span>
                                        <span class="text-muted">Since last week</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col mt-0">
                                            <h5 class="card-title">Projetos canceladas</h5>
                                        </div>
                                        <div class="col-auto">
                                            <div class="stat text-primary">
                                                <i class="align-middle" data-feather="x-circle"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <h1 class="mt-1 mb-3">$21.300</h1>
                                    <div class="mb-0">
                                        <span class="text-success"> <i class="mdi mdi-arrow-bottom-right"></i> 6.65%
                                        </span>
                                        <span class="text-muted">Since last week</span>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col mt-0">
                                            <h5 class="card-title">Projetos em preparação</h5>
                                        </div>
                                        <div class="col-auto">
                                            <div class="stat text-primary">
                                                <i class="align-middle" data-feather="clipboard"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <h1 class="mt-1 mb-3">64</h1>
                                    <div class="mb-0">
                                        <span class="text-danger"> <i class="mdi mdi-arrow-bottom-right"></i> -2.25%
                                        </span>
                                        <span class="text-muted">Since last week</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-6 col-xxl-7">
                <div class="card flex-fill w-100">
                    <div class="card-header">

                        <h5 class="card-title mb-0">Recent Movement</h5>
                    </div>
                    <div class="card-body py-3">
                        <div class="chart chart-sm">
                            <canvas id="chartjs-dashboard-line"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="row">
            <div class="col-12 col-lg-12 col-xxl-9 d-flex">
                <div class="card flex-fill">
                    <div class="card-header">

                        <h5 class="card-title mb-0">Ultimos Projetos</h5>
                    </div>
                    <table class="table table-hover my-0">
                        <thead>
                            <tr>
                                <th>Nome do projeto</th>
                                <th class="d-none d-xl-table-cell">Data inicio</th>
                                <th class="d-none d-xl-table-cell">Data fim</th>
                                <th>Status</th>
                                <th class="d-none d-md-table-cell">Responsavel</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Project Apollo</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-success">Done</span></td>
                                <td class="d-none d-md-table-cell">Vanessa Tucker</td>
                            </tr>
                            <tr>
                                <td>Project Fireball</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-danger">Cancelled</span></td>
                                <td class="d-none d-md-table-cell">William Harris</td>
                            </tr>
                            <tr>
                                <td>Project Hades</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-success">Done</span></td>
                                <td class="d-none d-md-table-cell">Sharon Lessman</td>
                            </tr>
                            <tr>
                                <td>Project Nitro</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-warning">In progress</span></td>
                                <td class="d-none d-md-table-cell">Vanessa Tucker</td>
                            </tr>
                            <tr>
                                <td>Project Phoenix</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-success">Done</span></td>
                                <td class="d-none d-md-table-cell">William Harris</td>
                            </tr>
                            <tr>
                                <td>Project X</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-success">Done</span></td>
                                <td class="d-none d-md-table-cell">Sharon Lessman</td>
                            </tr>
                            <tr>
                                <td>Project Romeo</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-success">Done</span></td>
                                <td class="d-none d-md-table-cell">Christina Mason</td>
                            </tr>
                            <tr>
                                <td>Project Wombat</td>
                                <td class="d-none d-xl-table-cell">01/01/2021</td>
                                <td class="d-none d-xl-table-cell">31/06/2021</td>
                                <td><span class="badge bg-warning">In progress</span></td>
                                <td class="d-none d-md-table-cell">William Harris</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/Projects.cshtml
@{
    ViewData["Title"] = "Projetos";
}
</nav>
<div class="content">
    <div class="container-fluid p-0">
        <div class="headerProjects" style="margin-bottom: 20px;">
            <h1 class="h3 mb-3"><strong>Projetos</strong></h1>
            <button class="btn btn-primary btn-lg"><i class="bi bi-plus-lg"></i> Novo projeto</button>
        </div>
        <div class="row">
            <div class="col-xl-6 col-xxl-7">
                <div class="card flex-fill w-100">
                    <div class="card-header">
                        <h5 class="card-title mb-0">_Nome do projeto</h5>
                    </div>
                    <div class="card-body py-3">
                        <div class="cardProjeto">
                            <div class="informacoes">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-xxl-7">
                <div class="card flex-fill w-100">
                    <div class="card-header">
                        <h5 class="card-title mb-0">_Nome do projeto</h5>
                    </div>
                    <div class="card-body py-3">
                        <div class="cardProjeto">
                            <div class="informacoes">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @* @{ var VbCardProject = ViewBag.VbCardProject;}
                @foreach (var item in VbCardProject)
                {
                <div class="col-xl-6 col-xxl-7">
                <div class="card flex-fill w-100">
                <div class="card-header">
                <h5 class="card-title mb-0">_Nome do projeto</h5>
                </div>
                <div class="card-body py-3">
                <div class="cardProjeto">
                <div class="informacoes">
                </div>
                </div>
                </div>
                </div>
                </div>
                } *@
        </div>
    </div>
</div>
<style>
    .cardProjeto {
        min-height: 210px;
        max-height: 210px;
    }
</style>

Views/Obra/Create.cshtml
@model ActivityManagement.Models.Obra

@{
    ViewData["Title"] = "Novo Projeto";
}
</nav>
<div class="content">
    <div class="container-fluid p-0">
        <h1>Novo Projeto</h1>
        <form asp-action="Create">
            <div class="row">
                <div class="form-group col-3">
                    <label class="control-label">Inicio do projeto</label>
                    <input type="date" asp-for="Inicio" class="form-control" />
                    <span asp-validation-for="Inicio" class="text-danger"></span>
                </div>
                <div class="form-group col-3">
                    <label class="control-label">Previsão</label>
                    <input type="date" asp-for="Previsao" class="form-control" />
                </div>
                <div class="form-group col-3 mt-2">
                    <label class="control-label">Fim do projeto</label>
                    <input type="date" asp-for="Termino" class="form-control" />
                </div>
                <div class="form-group col-3 mt-2">
                    <label class="control-label">Identificação do projeto</label>
                    <input asp-for="IdentificacaoDoProjeto" class="form-control" />
                    <span asp-validation-for="IdentificacaoDoProjeto" class="text-danger"></span>
                </div>
                <div class="form-group col-3 mt-2">
                    <label class="control-label">Chefe de Obra</label>
                    <input asp-for="ChefeDaObra" class="form-control" />
                    <span asp-validation-for="ChefeDaObra" class="text-danger"></span>
                </div>
                <div class="form-group col-3 mt-2">
                    <label class="control-label">Status</label>
                    <select class="form-select mb-3" asp-for="Status">
                        <option selected>Selecione</option>
                        <option value="1">Em andamento</option>
                        <option value="2">Finalizado</option>
                        <option value="3">Cancelado</option>
                    </select>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group col-3 mt-2">
                    <label asp-for="UF" class="control-label"></label>
                    <input asp-for="UF" class="form-control" />
                    <span asp-validation-for="UF" class="text-danger"></span>
                </div>
                <div class="form-group col-3 mt-2">
                    <label asp-for="Municipio" class="control-label"></label>
                    <input asp-for="Municipio" class="form-control" />
                    <span asp-validation-for="Municipio" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <input type="submit" value="Criar" class="btn btn-primary" />
                    <a asp-action="Index"><button class="btn btn-secondary">Voltar</button></a>
                </div>
        </form>
    </div>
</div>
</div>
</div>
</div>

Views/Obra/Delete.cshtml
@model ActivityManagement.Models.Obra

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Obra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Previsao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Previsao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Termino)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Termino)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentificacaoDoProjeto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentificacaoDoProjeto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChefeDaObra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChefeDaObra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Municipio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ActivityManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ActivityManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/app.css">
    <link rel="stylesheet" href="~/css/app.css.map">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
    <div class="wrapper">
        <nav id="sidebar" class="sidebar js-sidebar">
            <div class="sidebar-content js-simplebar">
                <a class="sidebar-brand" href="index.html">
                    <span class="align-middle">ActivityManagement</span>
                </a>

                <ul class="sidebar-nav">
                    <li class="sidebar-header">
                        Pages
                    </li>

                    <li class="sidebar-item active">
                        <a class="sidebar-link" asp-controller="Home" asp-action="Index" >
                            <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Painel</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Obra" asp-action="Index">
                            <i class="align-middle" data-feather="user"></i> <span class="align-middle">Projetos</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="pages-sign-in.html">
                            <i class="align-middle" data-feather="log-in"></i> <span class="align-middle">Sign In</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="pages-sign-up.html">
                            <i class="align-middle" data-feather="user-plus"></i> <span class="align-middle">Sign
                                Up</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" href="pages-blank.html">
                            <i class="align-middle" data-feather="book"></i> <span class="align-middle">Blank</span>
                        </a>
                    </li>
            </div>
        </nav>
        <div class="main">
            <nav class="navbar navbar-expand navbar-light navbar-bg">
                <a class="sidebar-toggle js-sidebar-toggle">
                    <i class="hamburger align-self-center"></i>
                </a>
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
        </div>
        </nav>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/app.js"></script>
        <script src="~/js/app.js.map"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
        <script src="https://cdn.amcharts.com/lib/5/percent.js"></script>
        <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>

</html>